encoding: utf-8

# SEO
title: 大蜕
description: 大蜕的个人博客
keywords: 大蜕, sddtc, blog
author: sddtc
footerText: 'Copyright © 2025'

# theme
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://www.sddtc.florist'
baseurl: ''

# 菜单
menu:
  - title: 首页
    url: /
  - title: 分类
    url: /pages/categories.html
  - title: 关于
    url: /pages/about.html
  - title: 项目
    url: /pages/projects.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

plugins:
  - jekyll-feed

feed:
  path: /static/xml/rss.xml
