[build]
	publish = "_site"
	command = "npm run build"

[[redirects]]
from = "/blog/*"
to = "/zh/blog/:splat"
status = 301
force = true

[[redirects]]
from = "/categories/*"
to = "/zh/categories/:splat"
status = 301
force = true

[[redirects]]
from = "/tags/*"
to = "/zh/tags/:splat"
status = 301
force = true

[[redirects]]
from = "/about/"
to = "/zh/about/"
status = 301
force = true
