name: Dependabot Auto merge

on:
  workflow_run:
    workflows: ["Dependabot PR Check"]
    types:
      - completed

jobs:
  do-stuff:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUBACTION_TOKEN }}
